
[general]
	placeholder = false

	[general.essentials]
		anti-monkey = false

	[general.party]
		party_commands = false

	[general."f7/m7"]
		text = ""

[kuudra]
	placeholder = false

[dungeons]
	leap_reminder = true

	[dungeons.terminals]
		"jenark's_terminals" = false
		custom_terminal_guis = false
		custom_term_gui = false

	[dungeons."f7/m7"]
		leap_reminder = false
		leap_reminder_text = "Leap to Healer!"

